/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all games */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of games */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameSummary"][];
                    };
                };
            };
        };
        put?: never;
        /** Create a new game */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateGameRequest"];
                };
            };
            responses: {
                /** @description Game created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get game state */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    gameId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current game state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a game */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    gameId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Game deleted successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Make a move */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    gameId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MoveRequest"];
                };
            };
            responses: {
                /** @description Move successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameResponse"];
                    };
                };
                /** @description Invalid move */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/ai-move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request AI to make a move */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    gameId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        playerId?: string;
                    };
                };
            };
            responses: {
                /** @description AI move successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{gameId}/next-round": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start next round */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    gameId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Next round started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GameResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/suggest-move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get AI move suggestion */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AISuggestionRequest"];
                };
            };
            responses: {
                /** @description AI suggestion */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AISuggestionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateGameRequest: {
            playerCount: number;
            playerConfigs: components["schemas"]["PlayerConfig"][];
        };
        PlayerConfig: {
            name: string;
            isAI: boolean;
        };
        GameResponse: {
            id?: string;
            players?: components["schemas"]["Player"][];
            currentPlayerId?: string;
            pyramid?: components["schemas"]["PlacedCard"][][];
            round?: number;
            totalRounds?: number;
            /** @enum {string} */
            gameStatus?: "setup" | "playing" | "roundEnd" | "gameEnd";
            eliminatedPlayers?: string[];
        };
        GameSummary: {
            id?: string;
            playerCount?: number;
            round?: number;
            totalRounds?: number;
            status?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        Player: {
            id?: string;
            name?: string;
            isAI?: boolean;
            cards?: components["schemas"]["Card"][];
            points?: number;
            isEliminated?: boolean;
        };
        Card: {
            id?: string;
            /** @enum {string} */
            color?: "green" | "yellow" | "red" | "purple" | "blue";
        };
        PlacedCard: {
            card?: components["schemas"]["Card"];
            position?: components["schemas"]["Position"];
            playerId?: string;
        } | null;
        Position: {
            row?: number;
            col?: number;
        };
        MoveRequest: {
            playerId: string;
            cardId: string;
            position: components["schemas"]["Position"];
        };
        AISuggestionRequest: {
            gameState: components["schemas"]["GameResponse"];
            playerId: string;
        };
        AISuggestionResponse: {
            cardId?: string;
            position?: components["schemas"]["Position"];
            confidence?: number;
        };
        Error: {
            message?: string;
            code?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
